export enum PeerTransferStatus {
  AUTHORIZED = 'AUTHORIZED',
  CLAIMED = 'CLAIMED',
  TRANSFERRING = 'TRANSFERRING',
  VERIFYING = 'VERIFYING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum PeerTransferTransport {
  LAN_DIRECT = 'LAN_DIRECT',
  P2P_DIRECT = 'P2P_DIRECT',
  P2P_RELAY = 'P2P_RELAY',
  CLOUD_FALLBACK = 'CLOUD_FALLBACK',
}
