export enum TransferStatus {
  QUEUED = 'QUEUED',
  PREPARING = 'PREPARING',
  TRANSFERRING = 'TRANSFERRING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  RETRYING = 'RETRYING',
}
