export enum StorageReplicaStatus {
  PENDING = 'PENDING',
  UPLOADING = 'UPLOADING',
  HEALTHY = 'HEALTHY',
  DEGRADED = 'DEGRADED',
  MISSING = 'MISSING',
  CORRUPTED = 'CORRUPTED',
  FAILED = 'FAILED',
  DELETING = 'DELETING',
  REPAIRING = 'REPAIRING',
}
