export enum CloudProvider {
  GOOGLE_DRIVE = 'GOOGLE_DRIVE',
  ONEDRIVE = 'ONEDRIVE',
  DROPBOX = 'DROPBOX',
  BOX = 'BOX',
  PCLOUD = 'PCLOUD',
  MEGA = 'MEGA',
  AWS_S3 = 'AWS_S3',
  CLOUDFLARE_R2 = 'CLOUDFLARE_R2',
  WASABI = 'WASABI',
  BACKBLAZE_B2 = 'BACKBLAZE_B2',
  DIGITALOCEAN_SPACES = 'DIGITALOCEAN_SPACES',
  AZURE_BLOB = 'AZURE_BLOB',
  GOOGLE_CLOUD_STORAGE = 'GOOGLE_CLOUD_STORAGE',
  ORACLE_OBJECT_STORAGE = 'ORACLE_OBJECT_STORAGE',
  IBM_COS = 'IBM_COS',
  CUSTOM_S3 = 'CUSTOM_S3',
  MEDIAFIRE = 'MEDIAFIRE',
}

export enum CloudAccountStatus {
  CONNECTED = 'CONNECTED',
  REAUTH_REQUIRED = 'REAUTH_REQUIRED',
  DISCONNECTED = 'DISCONNECTED',
  DEGRADED = 'DEGRADED',
  RATE_LIMITED = 'RATE_LIMITED',
  UNAVAILABLE = 'UNAVAILABLE',
  DISABLED = 'DISABLED',
}
